
development:
  adapter: mysql
  database: homemarks_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: homemarks_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: homemarks_production
  username: root
  password:
  host: localhost
